language: java
jdk: oraclejdk8
sudo: false

# Skipping installation phase
install: true

#services:
#- docker

cache:
  directories:
  - "$HOME/.cache"

deploy:
- provider: bintray
  file: target/.travis/core-bintray.json
  user: graygzou
  key: $BINTRAY_API_KEY
  skip_cleanup: true # to upload artifacts created during the build
  on:
    repo: dyga-entertainment/DygaEngine # Trigger build if build occurs in this branch
    tags: false  # Only if $TRAVIS_TAG is not set

- provider: bintray
  file: target/.travis/ui-bintray.json
  user: graygzou
  key: $BINTRAY_API_KEY
  skip_cleanup: true # to upload artifacts created during the build
  on:
    repo: dyga-entertainment/DygaEngine # Trigger build if build occurs in this branch
    tags: false  # Only if $TRAVIS_TAG is not set

  # TODO LATER
  # Automatic create release on github repo
  #- provider: releases
  #  skip_cleanup: true
  #  api_key: $GITHUB_OAUTH_API_KEY
  #  file_glob: true
  #  file:
  #    - "target/*.jar"
  #  on:
  #    repo: dyga-entertainment/DygaEngine
  #    tags: true

after_success:
  - mvn clean test jacoco:report coveralls:report -DrepoToken=$COVERALLS_TOKEN
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

notifications:
  email:
    recipients:
    - boiron.gregoire@gmail.com
    on_success: change
    on_failure: always