language: java
jdk: oraclejdk8
sudo: false

services:
- docker
cache:
  directories:
  - "$HOME/.cache"

deploy:
  provider: bintray
  file: "bintray.json"
  user: "graygzou"
  key: $BINTRAY_API_KEY
  skip_cleanup: true # to upload artifacts created during the build

notifications:
  email:
    recipients:
    - boiron.gregoire@gmail.com
    on_success: change
    on_failure: always